services:
  - type: web
    name: discord-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GUILD_ID
        sync: false
      - key: WELCOME_CHANNEL_ID
        sync: false
